### ISSUE TITLE
ImportError: cannot import name 'ParamSpec' from 'typing'

### ISSUE THREAD

**Issue by systelbbbb** [JustUndertaker/ComWeChatBotClient#49]
Traceback (most recent call last):
  File "D:\PJ\wxhook\ComWeChatBotClient-0.0.8\main.py", line 1, in <module>
    import wechatbot_client
  File "D:\PJ\wxhook\ComWeChatBotClient-0.0.8\wechatbot_client\__init__.py", line 8, in <module>
    from wechatbot_client.wechat import WeChatManager
  File "D:\PJ\wxhook\ComWeChatBotClient-0.0.8\wechatbot_client\wechat\__init__.py", line 7, in <module>
    from .wechat import WeChatManager as WeChatManager
  File "D:\PJ\wxhook\ComWeChatBotClient-0.0.8\wechatbot_client\wechat\wechat.py", line 7, in <module>
    from wechatbot_client.action_manager import (
  File "D:\PJ\wxhook\ComWeChatBotClient-0.0.8\wechatbot_client\action_manager\__init__.py", line 4, in <module>
    from .check import check_action_params as check_action_params
  File "D:\PJ\wxhook\ComWeChatBotClient-0.0.8\wechatbot_client\action_manager\check.py", line 6, in <module>
    from typing import Callable, ParamSpec, Type, TypeVar
ImportError: cannot import name 'ParamSpec' from 'typing' (D:\Programs\Python\Python39\lib\typing.py)

帮忙看看，我安装了这个模块的呀

**Comment by Lilneo786** [comment]
The error message you're encountering suggests that there is an issue with the ParamSpec import from the typing module in your code. The ParamSpec class is introduced in Python 3.10, so if you are using Python versions earlier than 3.10, you will encounter this error.

You can either upgrade to Python 3.10

OR

Modify the code: 

`from typing import Callable, Type, TypeVar`

**Comment by systelbbbb** [comment]
> The error message you're encountering suggests that there is an issue with the ParamSpec import from the typing module in your code. The ParamSpec class is introduced in Python 3.10, so if you are using Python versions earlier than 3.10, you will encounter this error.
> 
> You can either upgrade to Python 3.10
> 
> OR
> 
> Modify the code:
> 
> `from typing import Callable, Type, TypeVar`

Thank you very much, I didn't get any error after upgrading to 3.10.
